version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5000"
  product-service:
    build: ./product-service
    ports:
      - "5002:5000"
  order-service:
    build: ./order-service
    ports:
      - "5003:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
