name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4 # Using a more specific version for stability

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.2.0

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user-service Docker image
        run: |
          cd user-service
          docker build --push --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
          
      - name: Build and push frontend Docker image
        run: |
          cd frontend
          docker build --push --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.30.2'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          kubectl config view

      - name: Set Kubernetes context
        run: kubectl config use-context my-context

      - name: Update Kubernetes deployments
        env:
          KUBECONFIG: $HOME/.kube/config
        run: |
          kubectl set image deployment/user-service-deployment user-service=${{ secrets.DOCKER_USERNAME }}/user-service:latest
          kubectl set image deployment/frontend-deployment frontend=${{ secrets.DOCKER_USERNAME }}/frontend:latest
          kubectl rollout status deployment/user-service-deployment
          kubectl rollout status deployment/frontend-deployment
